/** @jsxImportSource @compiled/react */
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "../components/header";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div css={{ width: "100%", height: "100vh", backgroundColor: "#000000" }}>
        <Header />
      </div>
    </div>
  );
}
