/** @jsxImportSource @compiled/react */
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "../components/header";
import TokensList from "../components/tokensList";
import { Circles } from "react-loader-spinner";
import useTokens from "../utils/web3/tokens";

export default function Tokens() {
  return (
    <div
      css={{
        width: "100%",
        minHeight: "100vh",
        backgroundColor: "#000000",
        position: "relative",
      }}
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div
        css={{
          width: "100%",
          maxWidth: "1464px",
          padding: "0px 32px",
          margin: "auto",
          position: "relative",
          "@media (max-width: 991px)": {
            padding: "0px 30px",
          },
          "@media (max-width: 420px)": {
            padding: "0px 20px",
          },
        }}
      >
        <Header />
        <div
          css={{
            paddingTop: "100px",
          }}
        >
          <TokensList />
          {/* <Circles color="#917EFF" height={80} width={80} /> */}
        </div>
      </div>
    </div>
  );
}
